version: '3.4'
services:
  neo4j:
    container_name: "neo4j"
    image: neo4j:4.2.5
    volumes:
      - ./data:/data
      - ./conf:/var/lib/neo4j/conf
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
        - "NEO4J_AUTH:neo4j/neo4j"
    restart: always
